name: 'Setup Backend Linting Tools'
description: 'Install Python linting tools for backend'

runs:
  using: 'composite'
  steps:
    - name: Install linting tools
      shell: bash
      run: |
        cd backend
        pip install black isort pylint flake8
