name: 'Setup Python Backend'
description: 'Install Python, system dependencies, and Python packages for backend'

inputs:
  python-version:
    description: 'Python version to install'
    required: false
    default: '3.12'
  install-dev:
    description: 'Install development dependencies (linting, testing)'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    # Cache system dependencies to avoid apt-get update/install on every run
    - name: Cache system dependencies
      if: runner.os == 'Linux'
      id: cache-apt
      uses: actions/cache@v4
      with:
        path: |
          /var/cache/apt/archives
          /var/lib/apt/lists
        key: ${{ runner.os }}-apt-portaudio-${{ hashFiles('.github/actions/setup-python-backend/action.yml') }}
        restore-keys: |
          ${{ runner.os }}-apt-portaudio-

    - name: Install system dependencies (Ubuntu)
      if: runner.os == 'Linux' && steps.cache-apt.outputs.cache-hit != 'true'
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y portaudio19-dev

    - name: Set up Python with pip cache
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
        cache: 'pip'
        cache-dependency-path: |
          backend/requirements.txt
          backend/requirements-dev.txt
          backend/requirements-quality.txt

    - name: Install Python runtime dependencies
      shell: bash
      run: |
        cd backend
        pip install -r requirements.txt

    - name: Install Python development dependencies
      if: inputs.install-dev == 'true'
      shell: bash
      run: |
        cd backend
        pip install -r requirements-dev.txt
