name: 'Setup Python Backend'
description: 'Install Python, system dependencies, and Python packages for backend'

inputs:
  python-version:
    description: 'Python version to install'
    required: false
    default: '3.12'

runs:
  using: 'composite'
  steps:
    - name: Install system dependencies (Ubuntu)
      if: runner.os == 'Linux'
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y portaudio19-dev

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
        cache: 'pip'
        cache-dependency-path: backend/requirements.txt

    - name: Install Python dependencies
      shell: bash
      run: |
        cd backend
        pip install -r requirements.txt
