export const UPDATE_EMOTION = 'UPDATE_EMOTION';
export const UPDATE_WPM = 'UPDATE_WPM';
export const SET_CONNECTION_STATUS = 'SET_CONNECTION_STATUS';
export const SET_SESSION_STATUS = 'SET_SESSION_STATUS';
export const SET_RECORDING_STATUS = 'SET_RECORDING_STATUS';
export const ADD_ALERT = 'ADD_ALERT';
